name: Preview Deploy

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - name: Deploy to Vercel Preview
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --pre
